CREATE TABLE ACCESS_PARAMS(
    USERNAME VARCHAR(500),
    PASSWORD VARCHAR(500),
    URL VARCHAR(100)
);

INSERT INTO ACCESS_PARAMS VALUES ('Apibimer','12345678', 'https://512499bimerapi.alterdata.cloud/auth/token');

CREATE TABLE ERROR_LOG(
    OCURRENCEDATE TIMESTAMP,
    ID VARCHAR(100),
    REQUEST VARCHAR(1000),
    ERRORCODE INT,
    ERRORMESSAGE VARCHAR(4000),
    ERRORRESPONSEBODY VARCHAR(4000)
);
